# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/31_momos-for-wikiseealsotitles.ipynb.

# %% auto 0
__all__ = ['get_label_representation', 'get_label_remap']

# %% ../nbs/31_momos-for-wikiseealsotitles.ipynb 2
import os,torch, torch.multiprocessing as mp, pickle, numpy as np, scipy.sparse as sp
from transformers import DistilBertConfig

from xcai.basics import *
from xcai.models.oakY import OAK007, Encoder003
from xcai.models.distillation import DTL004,TCH001,TCH002

from xcai.clustering.cluster import BalancedClusters

from xclib.utils.sparse import retain_topk

from fastcore.utils import *

from xcai.core import Info
from xcai.data import MetaXCDataset

# %% ../nbs/31_momos-for-wikiseealsotitles.ipynb 4
os.environ['CUDA_VISIBLE_DEVICES'] = '2,3,4,5'
os.environ['WANDB_PROJECT']='mogic_00-wikiseealsotitles'

@patch
def get_label_representation(
    cls:DTL004,
    data_idx:Optional[torch.Tensor]=None,
    data_input_ids:Optional[torch.Tensor]=None,
    data_attention_mask:Optional[torch.Tensor]=None,
    **kwargs
):
    return cls.m_student.get_label_representation(data_idx, data_input_ids, data_attention_mask, **kwargs)

def get_cluster_mapping(embeddings:torch.Tensor, cluster_sz:int=3):
    clusters = BalancedClusters.proc(embeddings.half(), min_cluster_sz=cluster_sz)

    cluster_mapping = torch.zeros(embeddings.shape[0], dtype=torch.int64)
    for i,o in enumerate(clusters): cluster_mapping[o] = i

    return cluster_mapping, len(clusters)

@patch
def fuse_meta_into_embeddings(self:Encoder003, embed:torch.Tensor, meta_kwargs:Dict):
    meta_repr, bsz = {}, embed.size(0)
    
    for m_key, m_args in meta_kwargs.items():
        n_meta = m_args['data2ptr'].max()
        assert torch.all(m_args['data2ptr'] == n_meta), f'All datapoints should have same number of metadata.'
        
        m_input_ids, m_attention_mask = m_args['input_ids'], m_args['attention_mask']
        if m_input_ids.shape[0] > 0:
            m_embed = self.meta_encode(input_ids=m_input_ids, attention_mask=m_attention_mask)
        else:
            m_embed = torch.zeros(size=(0,768)).to(m_input_ids.device)
        meta_repr[m_key] = m_embed
                
        m_embed = m_embed.view(bsz, -1, self.config.dim)  
        fused_embed = self.cross_head(embed, m_embed)
        embed = embed + fused_embed
           
    return embed, meta_repr

# %% ../nbs/31_momos-for-wikiseealsotitles.ipynb 8
if __name__ == '__main__':
    build_block = False
    predict = True

    data_dir = '/data/datasets'
    pkl_dir = '/home/aiscuser/scratch1/datasets/'

    # output_dir = '/home/aiscuser/scratch1/outputs/mogic/12_momos-for-wikiseealsotitles-meta-encoder-002'
    output_dir = '/data/outputs/mogic/12_momos-for-wikiseealsotitles-meta-encoder-002'

    model_output = '/data/Projects/xc_nlg/outputs//67-ngame-ep-for-wikiseealso-with-input-concatenation-6-3'
    meta_embed_file = '/data/OGB_Weights/LF-WikiSeeAlsoTitles-320K/emb_weights.npy'

    """ Load data """
    pkl_file = f'{pkl_dir}/processed/wikiseealsotitles_data-lnk_distilbert-base-uncased_xcs.pkl'

    if build_block:
        block = XCBlock.from_cfg(data_dir, 'data_lnk', transform_type='xcs', tokenizer='distilbert-base-uncased', 
                                 sampling_features=[('lbl2data',4), ('lnk2data',3)], oversample=False)
        with open(pkl_file, 'wb') as file: pickle.dump(block, file)
    else:
        with open(pkl_file, 'rb') as file: block = pickle.load(file)

    """ Prune metadata """
    data_meta = retain_topk(block.train.dset.meta.lnk_meta.data_meta, k=5)
    lbl_meta = block.train.dset.meta.lnk_meta.lbl_meta
    block.train.dset.meta.lnk_meta.update_meta_matrix(data_meta, lbl_meta)

    # def load_metadata(meta_dir):
    #     data_cfg = {
    #         'info_column_names': ['identifier', 'input_text'],
    #         'use_tokenizer': True,
    #         'tokenizer': 'distilbert-base-uncased',
    #         'tokenization_column': 'input_text',
    #         'max_sequence_length': 32,
    #         'padding': False,
    #         'return_tensors': None,
    #     }
    #     return Info.from_txt(f'{meta_dir}/raw_data/category.raw.txt', **data_cfg)
    # 
    # old_meta_info = block.test.dset.meta.lnk_meta.meta_info
    # meta_dir = '/home/aiscuser/scratch1/datasets/LF-WikiSeeAlsoTitles-320K'
    # new_meta_info = load_metadata(meta_dir)

    # old_identifier = set(old_meta_info['identifier'])
    # new_idx = [i for i,o in enumerate(new_meta_info['identifier']) if o not in old_identifier]

    # new_meta_info = {k:[v[i] for i in new_idx] for k,v in new_meta_info.items()}

    # m1 = sp.load_npz('/home/aiscuser/scratch1/outputs/mogic/14_ngame-linker-for-wikiseealsotitles-001/predictions/test_predictions.npz')
    # m2 = sp.load_npz('/home/aiscuser/scratch1/outputs/mogic/14_ngame-linker-for-wikiseealsotitles-001/predictions/expanded_test_predictions.npz')
    # m2 = m2[:, new_idx]
    # data_meta = retain_topk(sp.hstack([m1,m2]), k=3)

    # lbl_meta = sp.csr_matrix((block.n_lbl, data_meta.shape[1]))

    # meta_info = {k: list(old_meta_info[k])+new_meta_info[k] for k in new_meta_info} 

    # block.test.dset.meta['lnk_meta'] = MetaXCDataset('lnk', data_meta, lbl_meta, meta_info)

    # data_meta = retain_topk(sp.load_npz('/home/aiscuser/scratch1/outputs/mogic/14_ngame-linker-for-wikiseealsotitles-001/predictions/test_predictions.npz'), k=3)

    data_meta = retain_topk(block.test.dset.meta.lnk_meta.data_meta, k=3)
    data_meta = sp.csr_matrix(data_meta.shape)
    lbl_meta = block.test.dset.meta.lnk_meta.lbl_meta
    block.test.dset.meta.lnk_meta.update_meta_matrix(data_meta, lbl_meta)

    block.collator.tfms.tfms[0].sampling_features = [('lbl2data',4),('lnk2data',3)]
    block.collator.tfms.tfms[0].oversample = False
    
    """ Training arguements """
    args = XCLearningArguments(
        output_dir=output_dir,
        logging_first_step=True,
        per_device_train_batch_size=512,
        per_device_eval_batch_size=512,
        representation_num_beams=200,
        representation_accumulation_steps=10,
        save_strategy="steps",
        evaluation_strategy="steps",
        eval_steps=5000,
        save_steps=5000,
        save_total_limit=5,
        num_train_epochs=300,
        predict_with_representation=True,
        adam_epsilon=1e-6,
        warmup_steps=100,
        weight_decay=0.01,
        learning_rate=2e-4,
        representation_search_type='BRUTEFORCE',
        
        output_representation_attribute='data_fused_repr',
        label_representation_attribute='data_repr',
        metadata_representation_attribute='data_repr',
        data_augmentation_attribute='data_repr',
        representation_attribute='data_fused_repr',
        clustering_representation_attribute='data_fused_repr',
    
        group_by_cluster=True,
        num_clustering_warmup_epochs=10,
        num_cluster_update_epochs=5,
        num_cluster_size_update_epochs=25,
        use_data_metadata_for_clustering=True,
        clustering_type='EXPO',
        minimum_cluster_size=2,
        maximum_cluster_size=1600,

        metric_for_best_model='P@1',
        load_best_model_at_end=True,
        target_indices_key='plbl2data_idx',
        target_pointer_key='plbl2data_data2ptr',
        
        use_distributional_representation=False,
        use_encoder_parallel=True,
        max_grad_norm=None, 
        fp16=True,
        
        label_names=['lbl2data_idx', 'lbl2data_input_ids', 'lbl2data_attention_mask', 'lnk2data_idx', 'lnk2data_input_ids', 'lnk2data_attention_mask'],
        
        prune_metadata=False,
        num_metadata_prune_warmup_epochs=10,
        num_metadata_prune_epochs=5,
        metadata_prune_batch_size=2048,
        prune_metadata_names=['lnk_meta'],
        use_data_metadata_for_pruning=True,
    
        predict_with_augmentation=False,
        use_augmentation_index_representation=True,
    
        data_aug_meta_name='lnk',
        augmentation_num_beams=None,
        data_aug_prefix='lnk',
        use_label_metadata=False,
        
        data_meta_batch_size=2048,
        augment_metadata=False,
        num_metadata_augment_warmup_epochs=10,
        num_metadata_augment_epochs=5,
    
        use_cpu_for_searching=True,
        use_cpu_for_clustering=True,
    )

    if predict:
        m_teacher = TCH001(DistilBertConfig(), n_data=block.train.dset.n_data, n_lbl=block.n_lbl)
        n_clusters = 131072

        bsz = max(args.per_device_train_batch_size, args.per_device_eval_batch_size)*torch.cuda.device_count()
        m_student = OAK007(DistilBertConfig(), batch_size=bsz, num_batch_labels=5000, 
                                       margin=0.3, num_negatives=10, tau=0.1, apply_softmax=True,
                                   
                                       data_aug_meta_prefix='lnk2data', lbl2data_aug_meta_prefix=None, 
                                       data_pred_meta_prefix=None, lbl2data_pred_meta_prefix=None,
                                       
                                       calib_margin=0.05, calib_num_negatives=10, calib_tau=0.1, calib_apply_softmax=False, 
                                       calib_loss_weight=0.1, use_calib_loss=False,

                                       n_labels=block.n_lbl, n_clusters=n_clusters,
        
                                       use_query_loss=True,
        
                                       use_encoder_parallel=True)
        
        os.environ['WANDB_MODE'] = 'disabled'

        mname = f'{output_dir}/{os.path.basename(get_best_model(output_dir))}'
        model = DTL004.from_pretrained(mname, m_student=m_student, m_teacher=m_teacher, bsz=bsz, tn_targ=5000, margin=0.3, tau=0.1, 
                       n_negatives=10, apply_softmax=True, teacher_data_student_label_loss_weight=1.0, 
                       student_data_teacher_label_loss_weight=0.0, data_mse_loss_weight=0.1, label_mse_loss_weight=0.0)

        metric = PrecRecl(block.n_lbl, block.test.data_lbl_filterer, prop=block.train.dset.data.data_lbl,
                          pk=10, rk=200, rep_pk=[1, 3, 5, 10], rep_rk=[10, 100, 200])

        learn = XCLearner(
            model=model, 
            args=args,
            eval_dataset=block.test.dset,
            data_collator=block.collator,
            compute_metrics=metric,
        )
        
        o = learn.predict(block.test.dset)
        print(o.metrics)
    else:
        m_teacher = TCH001.from_pretrained(f'{model_output}/teacher', n_data=block.train.dset.n_data, n_lbl=block.n_lbl)
        m_teacher.freeze_embeddings()

        label_cluster_mapping, n_clusters = get_cluster_mapping(m_teacher.lbl_repr.weight, cluster_sz=3)
        bsz = max(args.per_device_train_batch_size, args.per_device_eval_batch_size)*torch.cuda.device_count()
        m_student = OAK007.from_pretrained('sentence-transformers/msmarco-distilbert-base-v4', batch_size=bsz, num_batch_labels=5000, 
                                       margin=0.3, num_negatives=10, tau=0.1, apply_softmax=True,
                                   
                                       data_aug_meta_prefix='lnk2data', lbl2data_aug_meta_prefix=None, 
                                       data_pred_meta_prefix=None, lbl2data_pred_meta_prefix=None,
                                       
                                       calib_margin=0.05, calib_num_negatives=10, calib_tau=0.1, calib_apply_softmax=False, 
                                       calib_loss_weight=0.1, use_calib_loss=False,

                                       n_labels=block.n_lbl, n_clusters=n_clusters,
        
                                       use_query_loss=True,
        
                                       use_encoder_parallel=True)
        
        m_student.init_retrieval_head()
        m_student.init_cross_head()
        m_student.init_meta_encoder()

        m_student.init_label_embeddings()
        m_student.set_label_cluster_mapping(label_cluster_mapping)

        """ Distillation model """
        model = DTL004(DistilBertConfig(), m_student=m_student, m_teacher=m_teacher, bsz=bsz, tn_targ=5000, margin=0.3, tau=0.1, 
                       n_negatives=10, apply_softmax=True, teacher_data_student_label_loss_weight=1.0, 
                       student_data_teacher_label_loss_weight=0.0, data_mse_loss_weight=0.1, label_mse_loss_weight=0.0)
    
        """ Training """
        metric = PrecRecl(block.n_lbl, block.test.data_lbl_filterer, prop=block.train.dset.data.data_lbl,
                          pk=10, rk=200, rep_pk=[1, 3, 5, 10], rep_rk=[10, 100, 200])

        learn = XCLearner(
            model=model, 
            args=args,
            train_dataset=block.train.dset,
            eval_dataset=block.test.dset,
            data_collator=block.collator,
            compute_metrics=metric,
        )
        
        learn.train()
    
