# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mogic',
                'doc_host': 'https://suchith720.github.io',
                'git_url': 'https://github.com/suchith720/mogic',
                'lib_path': 'mogic'},
  'syms': { 'mogic.00_oak-for-wikiseealsotitles-trained-with-linker-predictions': { 'mogic.00_oak-for-wikiseealsotitles-trained-with-linker-predictions.XCLearner.create_optimizer_and_scheduler': ( 'oak-for-wikiseealsotitles-trained-with-linker-predictions.html#xclearner.create_optimizer_and_scheduler',
                                                                                                                                                                                                     'mogic/00_oak-for-wikiseealsotitles-trained-with-linker-predictions.py')},
            'mogic.01_oak-for-wikiseealsotitles-metadata-tokens': {},
            'mogic.02_oak-for-wikiseealsotitles-trained-with-groundtruth-metadata': {},
            'mogic.core': {'mogic.core.foo': ('core.html#foo', 'mogic/core.py')}}}
