# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mogic',
                'doc_host': 'https://suchith720.github.io',
                'git_url': 'https://github.com/suchith720/mogic',
                'lib_path': 'mogic'},
  'syms': { 'mogic.00_oak-for-wikiseealsotitles-random-metadata-param': {},
            'mogic.core': {'mogic.core.foo': ('core.html#foo', 'mogic/core.py')}}}
